---
- hosts: win
  tasks:
#    - name: Create env directory
#      win_file:
#        path: C:\env\
#        state: directory
#    - name: Download OpenShell config
#      win_get_url:
#        url: https://github.com/imkanami/desktop-dev-playbook/blob/main/roles/install-core-app/source/openshell/Settings.xml
#        dest: C:\env\Settings.xml
#    - name: Download OpenShell skin
#      win_get_url:
#        url: https://github.com/imkanami/desktop-dev-playbook/blob/main/roles/install-core-app/source/openshell/Fluent-Metro.skin
#        dest: C:\env\Fluent-Metro.skin       
#    - name: Download OpenShell setup
#      win_get_url:
#        url: https://github.com/Open-Shell/Open-Shell-Menu/releases/download/4.4.169-beta/OpenShellSetup_4_4_169.exe
#        dest: C:\env\OpenShellSetup_4_4_169.exe
    - name: Install Open-shell
      win_package:
        path: https://github.com/Open-Shell/Open-Shell-Menu/releases/download/4.4.169-beta/OpenShellSetup_4_4_169.exe
        product_id: '{313D2BD7-C719-4A0C-A39B-21B383219402}'
        arguments: '/qn ADDLOCAL=StartMenu'
        state: present
    - name: Check if Settings.xml files exists
      win_stat: 
        path: C:\Program Files\Open-Shell\Settings.xml
      register: result_1
    - name: Check if Skin files exists
      win_stat: 
        path: C:\Program Files\Open-Shell\Skins\Fluent-Metro.skin7
      register: result_2
    - name: Download config files
      win_get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
      loop:
        - { url: 'https://raw.githubusercontent.com/imkanami/desktop-dev-playbook/main/roles/install-core-app/source/openshell/Settings.xml', dest: 'C:\Program Files\Open-Shell\Settings.xml' }
        - { url: 'https://github.com/imkanami/desktop-dev-playbook/raw/main/roles/install-core-app/source/openshell/Fluent-Metro.skin7', dest: 'C:\Program Files\Open-Shell\Skins\Fluent-Metro.skin7' }
      when: result_1.stat.exists == false or result_2.stat.exists == false